### ISSUE TITLE
Issue with LabGuru Authenticate

### ISSUE THREAD

**Issue by Sean-Riordan-PhD** [BioData/LabguruR#6]
labguru_authenticate is returning an error message even though my password and username are correct. I've tried inputting my data in multiple ways. Any suggestions?

> labguru_authenticate(smriordan@cm.edu,YC&#h2,server = "https://jonathan.labguru.com", set_sys = TRUE)
Error: unexpected symbol in "labguru_authenticate(smriordan@cm.edu,YC&3pwTZ3"
> labguru_authenticate("smriordan@cmh.edu","YC&#h2",server = "https://jonathan.labguru.com", set_sys = TRUE)
Error in labguru_authenticate("smriordan@cmh.edu", "YC&#h2", server = "https://jonathan.labguru.com",  : 
  Invalid credentials
> labguru_authenticate(email    = "smriordan@cmh.edu",
+                      password = "YC&#h2",
+                      server   = "https://jonathan.labguru.com")
Error in labguru_authenticate(email = "smriordan@cmh.edu", password = "YC&#h2",  : 
  Invalid credentials

**Comment by Sean-Riordan-PhD** [comment]
So I was curious about the jonathan.labguru.com thing. I thought that was just something specific for R but when I changed it to my.labguru.com it worked. Is this something I was just supposed to know to change? I feel like the help file should spell that out.

**Comment by jgross** [comment]
@Sean-Riordan-PhD thanks for spotting this - I've fixed the default to be 'https://my.labguru.com'

**Comment by jgross** [comment]
I've changed the default to be my.labguru.com;
however, this is stated in the 'authenticate' section of the readme;

**Comment by Sean-Riordan-PhD** [comment]
Thanks Jonathan,
I must have missed that in the authenticate section.

Sean
